#!/usr/bin/env node
/**
 * Emits worker/src/static_assets.generated.ts with the frontend files embedded
 * as escaped string literals (JSON.stringify), so the Worker bundle is fully
 * self-contained and needs no static-assets store or special esbuild loader.
 *
 * Usage: node worker/scripts/generate-static.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const files = {
  indexHtml: "frontend/index.html",
  adminHtml: "frontend/admin.html",
  frameforgeCss: "frontend/css/frameforge.css",
  apiJs: "frontend/js/api.js",
  userJs: "frontend/js/user.js",
  adminJs: "frontend/js/admin.js",
};

const out = Object.entries(files)
  .map(([name, path]) => `export const ${name}: string = ${JSON.stringify(readFileSync(join(root, path), "utf8"))};`)
  .join("\n\n");

const outPath = join(root, "worker", "src", "static_assets.generated.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `// AUTO-GENERATED by worker/scripts/generate-static.mjs — do not edit.\n\n${out}\n`);
console.log(`Wrote ${outPath} (${out.length} bytes)`);
