#!/usr/bin/env node
/**
 * Emits worker/src/static_assets.generated.ts with the frontend files embedded
 * as escaped string literals (JSON.stringify), plus the STATIC_ASSETS route
 * map with content types. The Worker bundle is fully self-contained and needs
 * no static-assets store or special esbuild loader.
 *
 * This file is the single source of truth for what the worker serves: adding a
 * frontend file means adding one entry here — the generated module and
 * worker/src/static.ts re-export it automatically.
 *
 * Usage: node worker/scripts/generate-static.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const assets = [
  { name: "indexHtml", route: "/", file: "frontend/index.html", contentType: "text/html; charset=utf-8" },
  { name: "indexHtml", route: "/index.html", file: "frontend/index.html", contentType: "text/html; charset=utf-8" },
  { name: "adminHtml", route: "/admin.html", file: "frontend/admin.html", contentType: "text/html; charset=utf-8" },
  { name: "frameforgeCss", route: "/css/frameforge.css", file: "frontend/css/frameforge.css", contentType: "text/css; charset=utf-8" },
  { name: "apiJs", route: "/js/api.js", file: "frontend/js/api.js", contentType: "application/javascript; charset=utf-8" },
  { name: "sha256Js", route: "/js/sha256.js", file: "frontend/js/sha256.js", contentType: "application/javascript; charset=utf-8" },
  { name: "userJs", route: "/js/user.js", file: "frontend/js/user.js", contentType: "application/javascript; charset=utf-8" },
  { name: "adminJs", route: "/js/admin.js", file: "frontend/js/admin.js", contentType: "application/javascript; charset=utf-8" },
];

const named = {};
const seen = new Set();
const lines = [];
for (const a of assets) {
  if (seen.has(a.name)) continue;
  seen.add(a.name);
  const src = readFileSync(join(root, a.file), "utf8");
  named[a.name] = src;
  lines.push(`export const ${a.name}: string = ${JSON.stringify(src)};`);
}

lines.push("");
lines.push(`export interface StaticAsset {`);
lines.push(`  data: string;`);
lines.push(`  contentType: string;`);
lines.push(`}`);
lines.push("");
lines.push(`export const STATIC_ASSETS: Record<string, StaticAsset> = {`);
for (const a of assets) {
  lines.push(`  ${JSON.stringify(a.route)}: { data: ${a.name}, contentType: ${JSON.stringify(a.contentType)} },`);
}
lines.push(`};`);

const out = lines.join("\n");
const outPath = join(root, "worker", "src", "static_assets.generated.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `// AUTO-GENERATED by worker/scripts/generate-static.mjs — do not edit.\n\n${out}\n`);
console.log(`Wrote ${outPath} (${out.length} bytes)`);
