// Route map + content types for the inlined frontend assets live in
// static_assets.generated.ts (generated by worker/scripts/generate-static.mjs).
export { STATIC_ASSETS } from "./static_assets.generated";
export type { StaticAsset } from "./static_assets.generated";
